config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  resources :users
  
  get '/contact'=> 'staticpages#contact'
  get '/home'=> 'staticpages#home', as: 'home_path'
  get '/about'=> 'staticpages#about'
  get '/help'=> 'staticpages#help',as: 'help_path'
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new',as: 'login_path'
  post '/login'=> 'sessions#create'
  delete '/logout' => 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true,length: {maximum: 50}
  email_regex = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:true,uniqueness: true, format:{with: email_regex}
  validates :password,presence: true,length: { minimum: 6}
  def User.new_token
    securRandom.urlsafe_bade64
    attr_accessor :remember_token
  end
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest,User.digest(remember_token))
    
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email:params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  def destroy
   log_out
   redirect_to home_path_url
    
  end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
    
  end
  def contact
    
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end
  def new
    @user = User.new
  end
  def show
    @user = User.find(params[:id])

  end
  def create
  @user = User.new(user_params)
  if @user.save
    login @user
    flash[:success]= 'Welcome to the Semple App'
    redirect_to login_path
  else
    render 'new'
  end
end
private
def user_params
  params.require(:user).permit(:name,:email,:password,:password_confirmation)
  
end
end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
        
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
      end
      #return true if the user is logged in,false otherways
      def logged_in?
        !current_user.nil?
      end
        #logout current user
        def log_out
            
            session.delete(:user_id)
            @current_user =nil
        end
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "http://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url,alt:user.name,class: "gravatar")
        
    end
end

app/views/layouts/_footer.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="css/style.css" rel="stylesheet">
    </head>
    <body>
        <footer class='footer'>
            <small>
                The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
                By <a href="http://www.michaelhartl.com/">Michael Hartl</a>
            </small>
            <nav>
                <ul>
                <li><%= link_to "About",about_path %> </li>
                <li><%= link_to "Contact",contact_path %> </li>
                <li><a href="http://news.railstutorial.org/">News</a> </li>
                </ul>
            </nav>
        </footer>
    
    </body>
</html>

app/views/layouts/_header.html.erb
<header class='navbar naebar-fixed-top navbar-inverse'>
    <div class='container'>
      <%= link_to "simple app",home_path_url,id:"logo" %>
      <nav>
        <ul class='nav navbar-nav navbar-right'>
          <li><%= link_to "Home",home_path_url %></li>
          <li> <%= link_to "Help", help_path_url %></li>
          <% if logged_in? %>
          <li><%= link_to "Users","#" %></li>
          <li class='dropdown'>
          <a href="#" class='dropdown-toggle'data-toggle='dropdown'>Account <b class='carete'></b></a>
          <ul class='dropdown-menu'>
            <li><%= link_to "profile",current_user %></li>
            <li><%= link_to "settings","#" %></li>
            <li><%= link_to "divider" %></li>
            <li><%= link_to "log out",logout_path,method:"delete" %></li>
          </ul>
          </li>
          <% else %>
          <li><%= link_to "log in",login_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>

app/views/layouts/_shim.html.erb
<!--(if it IE)>
<scripts arc='//cdnjs.cloudflare.com/ajax/li'-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title></title>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    
    <%= render 'layouts/header' %>
    <div class='container'>
      <% flash.each do |message_type,message| %>
      <div class='alert alert-<%= message_type %>'><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    
  </body>
</html>
      
        
      

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id='error_explanation'>
        <div class='alert alert-danger'>
            The form contains <%= pluralize(@user.errors.count,'error')%>
        </div>  
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
    <% end %>

app/views/staticpages/about.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Testing</title>
</head>
<body>
    <h1>Hello World</h1>
    
</body>
</html>

app/views/staticpages/contact.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="css/style.css" rel="stylesheet">
    </head>
    <body>
        <h1>Contact</h1>
        <p>contact us:
        <a href="http://www.railstutorial.org/contact">contact page</a>
        </p>
    </body>
</html>

app/views/staticpages/help.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="css/style.css" rel="stylesheet">
    </head>
    <body>
        <h1>help</h1>
    </body>
</html>

app/views/staticpages/home.html.erb
<div class='center jumbotron'>
    <h1> Welcome the Dating app </h1>
    
    <h2>
        this is the page for the 
        <a href="http://www.railstutorial.org/">Ruby on Rails tutorial"</a>
        sameple application.
    </h2>
    <%= link_to "Sign up now",signup_path,class:"btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("rails.png",alt:"Rails logo"),'http://rubyonrails.org' %>


<style>
    img {
        width:80px;
    }

app/views/users/index.html.erb
<div class='containet'>
    <div class='card'>
    <table class='border= 1S'>
        <thead>
            <th>Name</th>
            <th>email</th>
            <th>organization</th>S
        </thead>
        <tbody>
            <tr>
                <td><%= @user.name%></td>
                <td><%= @user.email%></td>
                <td><%= @user.name%></td>
            </tr>
        </tbody>
    </table>
        
    </div>
    
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <form action="/users" method="post" class="form">
        <%= render 'shared/error_messages' %>
            <div class='form-group'>
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"
                    class='form-control'>
            </div>
            <div class='form-group'>
                <input type="text" name="user[name]" value="" class="form-control" placeholder="First name">
            </div>
            <div class='form-group'>
                <input type="email" name="user[email]" value="" class="form-control" placeholder=" email">
            </div>
            <div class='form-group'>
                <input type="password" name="user[password]" value="" class="form-control" placeholder=" password">
            </div>
            <div class='form-group'>
                <input type="password" name="user[password_confirmation]" value="" class="form-control"
                    placeholder="password confirmation">
                <div class='form-group'>
                    <button class="btn btn-primary" type='submit'>Create My Account</button>
                </div>
        </form>
    </div>
    <div class="col-md-2"></div>
</div>

app/views/users/show.html.erb
<div class='row'>
    <aside class='col-md-4'>
        <section class='user_info'>
            <h1>
                <%= gravatar_for @user %>
                <%= @user.name %>
            </h1>
        </section>
    </aside>
</div>